### ISSUE TITLE
Would Love To Be A Member Of lispXXX

### ISSUE THREAD

**Issue by aryashah2k** [lispXXX/join-our-team#1]
Hey there, I would love to be a part of this community and hereby request the owners to send an invite to join the same.

My Github ID: aryashah2k

I am fairly new to Lisp and am loving the language. I have some good use cases in mind which could help this community grow. I shall be a part of this workflow and contribute to the existing objectives that the organization and the community have in common!

**Comment by aryashah2k** [comment]
Successfully joined the Org.

**Comment by jbampton** [comment]
https://discord.gg/PW3Fh9Knpp
