### ISSUE TITLE
Request To Join Organization.

### ISSUE THREAD

**Issue by iabdr** [lispXXX/join-our-team#10]
I’m Abd, a Student, Developer, Learner and Graphic Designer.
I’m interested in Web & App Development.
I’m currently learning Flutter, React Native & Python.

**Comment by jbampton** [comment]
Invite is now sent 💯

**Comment by trudever** [comment]
I want to join

**Comment by codomposer** [comment]
Please invite me
I hope I can contribute to this organization

**Comment by JhonnyLusonode** [comment]
I would love to join this organization :D
